# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:44
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('member', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('about', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('picture', models.URLField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'get_latest_by': 'date_joined',
            },
        ),
    ]
