# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180317_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
    ]
