# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 13:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ready'), (1, 'Start'), (2, 'Close')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(related_name='tournament_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='users',
            field=models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
