# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180327_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'ordering': ('-id',), 'verbose_name': 'Tournament Match', 'verbose_name_plural': 'Tournament Matches'},
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
