# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[('CYCLE', 'Cycle'), ('SPELL_BAIT', 'Spell Bait'), ('BEATDOWN', 'Beatdown'), ('SPAWNER', 'Spawner'), ('THREE_CROWNS', 'Three Crowns'), ('CONTROL', 'Control'), ('SIEGE', 'Siege')])),
                ('avg_elixir', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
