# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cards', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'Cycle'), (2, 'Spell Bait'), (3, 'Beatdown'), (4, 'Spawner'), (5, 'Three Crowns'), (6, 'Control'), (7, 'Siege')])),
                ('avg_elixir', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['-date_created'],
                'get_latest_by': 'date_created',
            },
        ),
    ]
