# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Cycle'), (2, 'Spell Bait'), (3, 'Beatdown'), (4, 'Spawner'), (5, 'Three Crowns'), (6, 'Control'), (7, 'Siege')]),
        ),
    ]
