# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20180301_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'get_latest_by': 'date_created', 'ordering': ['-date_created'], 'verbose_name': 'Deck', 'verbose_name_plural': 'Decks'},
        ),
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(default='deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
