# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20180301_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='slug',
        ),
    ]
