# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20180311_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='arena',
            field=models.IntegerField(choices=[(0, 'All Arenas'), (1, 'Training Camp'), (2, 'Goblin Stadium'), (3, 'Bone Pit'), (4, 'Barbarian Bowl'), (5, "P.E.K.K.A.'s Playhouse"), (6, 'Spell Valley'), (7, 'Builders Workshop'), (8, 'Royal Arena'), (9, 'Frozen Peak'), (10, 'Jungle Arena'), (11, 'Hog Mountain'), (12, 'Electro Valley'), (13, 'Legendary Arena')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='for_1v1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='for_2v2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='for_2x',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='for_3x',
            field=models.BooleanField(default=True),
        ),
    ]
