# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_auto_20180313_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='for_1v1',
            new_name='mode_1v1',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='for_2v2',
            new_name='mode_2v2',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='for_2x',
            new_name='mode_2x',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='for_3x',
            new_name='mode_3x',
        ),
    ]
