# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='issuer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
